plugins:
  - jekyll-archives
permalink: /:year/:month/:day/:title
paginate: 7
jekyll-archives:
  enabled:
   - tags
   - categories
  layouts:
    year: year-archive
    category: categories-archive
    tag: categories-archive
  permalinks:
    tag: '/tag/:name/'
    category: '/:name/'
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - divshot.json
  - _site
  - circle.yml
  - divshot.json
production: true
production_url: https://jonas.brusman.se
title : Jonas Brusman
author:
  name: Jonas Brusman
  email: jonas@brusman.se
  github: himynameisjonas
  twitter: himynameis jonas
sass:
  sass_dir: assets/_sass
