permalink: /:year/:month/:day/:title
pygments: true
paginate: 10
var:
  archive_path: /archive.html
exclude: ['jekyll', 'bin', 'vendor', 'Gemfile', 'Gemfile.lock', 'Procfile', 'jekyll.thor', 'unicorn.rb', 'subdomains']
destination: 'jekyll'
production: true

pygments: true
production_url: http://jonasforsberg.se
title : Jonas Forsberg
author:
  name: Jonas Forsberg
  email: hello@jonasforsberg.se
  github: himynameisjonas
  twitter: himynameisjonas
prose:
  metadata:
    "_posts":
      layout: post
      title: "A new post"
      flickr:
      - http://www.flickr.com/photos/himynameisjonas/6872156519/
      tags:
      - photo