# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title 
auto: true
pygments: true
paginate: 10
var:
  archive_path: /archive.html
exclude: ['public']

production_url : http://username.github.com # or your custom domain name
title : Jonas Forsberg
author:
  name: Jonas Forsberg
  email: hello@jonasforsberg.se
  github: himynameisjonas
  twitter: himynameisjonas

# http://johntornow.com/
# http://log.maniacalrage.net/
